export { default as useTrending } from "./useTrending";
export { default as useDiscover } from "./useDiscover";
export { default as useGenres } from "./useGenres";
export { default as useMovieDetail } from "./useMovieDetail";
export { default as useTvShowDetail } from "./useTvShowDetail";
export { default as useCollection } from "./useCollection";
export { default as useRecommendations } from "./useRecommendations";
export { default as useCredits } from "./useCredits";
export { default as usePersonDetail } from "./usePersonDetail";
